name: 'Terraform Apply'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-*.yml'

env:
  TF_VERSION: '1.6.6'
  TF_WORKING_DIR: './terraform'

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    
    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
    
    - name: 'Terraform Init'
      id: init
      run: terraform init
    
    - name: 'Terraform Plan'
      id: plan
      run: terraform plan -no-color -out=tfplan
    
    - name: 'Terraform Apply'
      id: apply
      run: terraform apply -auto-approve tfplan
    
    - name: 'Upload Generated Files'
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: terraform-generated-files
        path: ${{ env.TF_WORKING_DIR }}/generated/
        retention-days: 30
    
    - name: 'Terraform Output'
      id: output
      run: terraform output -json > terraform_outputs.json
    
    - name: 'Upload Terraform Outputs'
      uses: actions/upload-artifact@v4
      with:
        name: terraform-outputs
        path: ${{ env.TF_WORKING_DIR }}/terraform_outputs.json
        retention-days: 30
